[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn similarity.main:app --host 0.0.0.0 --port $PORT"
